-- 用户表
CREATE TABLE IF NOT EXISTS `user` (
    `id` BIGINT NOT NULL COMMENT '用户ID',
    `user_account` VARCHAR(50) NOT NULL COMMENT '用户账号',
    `user_password` VARCHAR(100) NOT NULL COMMENT '用户密码',
    `user_name` VARCHAR(50) DEFAULT NULL COMMENT '用户昵称',
    `user_avatar` VARCHAR(500) DEFAULT NULL COMMENT '用户头像',
    `user_profile` VARCHAR(500) DEFAULT NULL COMMENT '用户简介',
    `user_role` VARCHAR(20) NOT NULL DEFAULT 'student' COMMENT '用户角色：student-学生，hr-企业HR，admin-管理员',
    `education` VARCHAR(50) DEFAULT NULL COMMENT '学历',
    `major` VARCHAR(50) DEFAULT NULL COMMENT '专业',
    `skills` VARCHAR(500) DEFAULT NULL COMMENT '技能',
    `graduation_year` INT DEFAULT NULL COMMENT '毕业年份',
    `school` VARCHAR(100) DEFAULT NULL COMMENT '学校',
    `company_name` VARCHAR(100) DEFAULT NULL COMMENT '公司名称',
    `position` VARCHAR(50) DEFAULT NULL COMMENT '职位',
    `phone` VARCHAR(20) DEFAULT NULL COMMENT '手机号',
    `email` VARCHAR(100) DEFAULT NULL COMMENT '邮箱',
    `resume_url` VARCHAR(500) DEFAULT NULL COMMENT '简历链接',
    `user_status` INT DEFAULT 0 COMMENT '用户状态：0-正常，1-禁用',
    `edit_time` DATETIME DEFAULT NULL COMMENT '编辑时间',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `is_delete` INT DEFAULT 0 COMMENT '是否删除：0-未删除，1-已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_user_account` (`user_account`),
    KEY `idx_user_role` (`user_role`),
    KEY `idx_user_status` (`user_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';

-- 公司表
CREATE TABLE IF NOT EXISTS `company` (
    `id` BIGINT NOT NULL COMMENT '公司ID',
    `company_name` VARCHAR(100) NOT NULL COMMENT '公司名称',
    `company_desc` TEXT DEFAULT NULL COMMENT '公司简介',
    `industry` VARCHAR(50) DEFAULT NULL COMMENT '所属行业',
    `company_size` VARCHAR(50) DEFAULT NULL COMMENT '公司规模',
    `company_address` VARCHAR(200) DEFAULT NULL COMMENT '公司地址',
    `company_logo` VARCHAR(500) DEFAULT NULL COMMENT '公司Logo',
    `website` VARCHAR(200) DEFAULT NULL COMMENT '公司官网',
    `contact_person` VARCHAR(50) DEFAULT NULL COMMENT '联系人',
    `contact_phone` VARCHAR(20) DEFAULT NULL COMMENT '联系电话',
    `contact_email` VARCHAR(100) DEFAULT NULL COMMENT '联系邮箱',
    `company_status` INT DEFAULT 0 COMMENT '公司状态：0-正常，1-已禁用',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `is_delete` INT DEFAULT 0 COMMENT '是否删除：0-未删除，1-已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_company_name` (`company_name`),
    KEY `idx_industry` (`industry`),
    KEY `idx_company_status` (`company_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='公司表';

-- 职位表
CREATE TABLE IF NOT EXISTS `position` (
    `id` BIGINT NOT NULL COMMENT '职位ID',
    `position_name` VARCHAR(100) NOT NULL COMMENT '职位名称',
    `company_name` VARCHAR(100) NOT NULL COMMENT '公司名称',
    `company_id` BIGINT DEFAULT NULL COMMENT '公司ID',
    `position_desc` TEXT DEFAULT NULL COMMENT '职位描述',
    `requirements` TEXT DEFAULT NULL COMMENT '职位要求',
    `salary_range` VARCHAR(50) DEFAULT NULL COMMENT '薪资范围',
    `work_location` VARCHAR(100) DEFAULT NULL COMMENT '工作地点',
    `education` VARCHAR(50) DEFAULT NULL COMMENT '学历要求',
    `major` VARCHAR(50) DEFAULT NULL COMMENT '专业要求',
    `skills` VARCHAR(500) DEFAULT NULL COMMENT '技能要求',
    `work_years` INT DEFAULT NULL COMMENT '工作年限要求',
    `position_type` VARCHAR(50) DEFAULT NULL COMMENT '职位类型：全职、兼职、实习',
    `tags` VARCHAR(500) DEFAULT NULL COMMENT '职位标签，多个标签用逗号分隔',
    `position_status` INT DEFAULT 0 COMMENT '职位状态：0-正常，1-已关闭，2-已招满',
    `view_count` INT DEFAULT 0 COMMENT '浏览次数',
    `apply_count` BIGINT DEFAULT 0 COMMENT '申请次数',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `is_delete` INT DEFAULT 0 COMMENT '是否删除：0-未删除，1-已删除',
    PRIMARY KEY (`id`),
    KEY `idx_company_id` (`company_id`),
    KEY `idx_position_type` (`position_type`),
    KEY `idx_position_status` (`position_status`),
    KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='职位表';
